### ISSUE TITLE
Problem opening some games.

### ISSUE THREAD

**Issue by Soarum10** [shonumi/gbe-plus#150] opened 2023-07-22 10:26 UTC
https://drive.google.com/drive/folders/1vZs67n_tQpRiGGIrW_1NX_hfQ3JydLx8?usp=sharing

Above there is a folder with the download of gbe-plus.

It was not working so I did a fix using new dll files and a new tasks.json file, that fixes my issue, but now when I play SpongeBob SquarePants - Legend of the Lost Spatula, or SpongeBob SquarePants - Battle for Bikini Bottom, it just says Eurasia and a weird thing and crashes. LOGS: GBE+ 1.2 [Qt]
MMU::Initialized
CPU::Initialized
GBE::Launching GBA core
MMU::Game Title - SBSPBATTLEBB
MMU::Game Code - BSQE
MMU::Maker Code - 78
MMU::ROM Size: 8192KB
MMU::ROM CRC32: a3674e7e
MMU::C:/Users/Aryaman/Downloads/SpongeBob SquarePants - Battle for Bikini Bottom (U) [hI]/SpongeBob SquarePants - Battle for Bikini Bottom (U) [hI].gba loaded successfully.
LCD::Initialized
APU::Initialized
JOY::No joysticks detected
JOY::Could not init rumble
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning - ARM.7 R15 used as Rm
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
Out of bounds write : 0xae5c8000
Out of bounds write : 0xae5c8001
Out of bounds read : 0xae5c8000
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning - ARM.10 Offset Register is PC
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning - ARM.10 Offset Register is PC
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning - ARM.10 Offset Register is PC
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
Out of bounds read : 0xffffd207
Out of bounds read : 0xffffd206
Out of bounds read : 0xffffd205
Out of bounds read : 0xffffd204
Out of bounds read : 0xffffd203
Out of bounds read : 0xffffd202
Out of bounds read : 0xffffd201
Out of bounds read : 0xffffd200
Out of bounds read : 0xffffd1ff
Out of bounds read : 0xffffd1fe
Out of bounds read : 0xffffd1fd
Out of bounds read : 0xffffd1fc
Out of bounds read : 0xffffd1fb
Out of bounds read : 0xffffd1fa
Out of bounds read : 0xffffd1f9
Out of bounds read : 0xffffd1f8
Out of bounds read : 0xffffd1f7
Out of bounds read : 0xffffd1f6
Out of bounds read : 0xffffd1f5
Out of bounds read : 0xffffd1f4
Out of bounds read : 0xffffd1f3
Out of bounds read : 0xffffd1f2
Out of bounds read : 0xffffd1f1
Out of bounds read : 0xffffd1f0
Out of bounds read : 0xffffd1ef
Out of bounds read : 0xffffd1ee
Out of bounds read : 0xffffd1ed
Out of bounds read : 0xffffd1ec
Out of bounds read : 0xffffd1eb
Out of bounds read : 0xffffd1ea
Out of bounds read : 0xffffd1e9
Out of bounds read : 0xffffd1e8
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0xff
Out of bounds read : 0xfffc0001
Out of bounds read : 0xfff40011
CPU::Warning: ARM instruction uses reserved conditional code NV
SWI::Error - Unknown BIOS function 0x97
CPU::Warning: ARM instruction uses reserved conditional code NV
MMU::Shutdown
CPU::Shutdown
APU::Shutdown
LCD::Shutdown.

**Comment by Soarum10** [comment] 2023-07-22 10:27
SOMEBODY FIX THIS.

**Comment by shonumi** [comment] 2023-08-15 16:52
Marking this as a duplicate of Issue #148.

**Closed by shonumi** 2023-08-15 16:52 UTC
Labels: duplicate
