### ISSUE TITLE
Program fails to compile on msys2

### ISSUE THREAD

**Issue by autofire372** [shonumi/gbe-plus#69] opened 2018-04-25 19:30 UTC
GBE+ currently does not compile on Windows under msys2 due to a bunch of "undefined reference" errors as soon as the GUI starts to build. I was using gcc 7.3.

**Comment by shonumi** [comment] 2018-04-26 02:13
Looks like your development environment is misconfigured. Those undefined references sound like gcc can't find the Qt libraries either during linking or it can't find Qt headers during compilation. None of that happens on my end. I'm on gcc 6.2.0, but it compiles fine across other versions (as old as 4.8.2). I doubt gcc would introduce anything that would break compiling GBE+ in such a major way like this. A couple of things:

1) Have you installed the Qt development libraries for msys2? Assuming you're using MinGW, you'll want something that looks like **mingw-w64-i686-qt5**. Optionally, GBE+ works just fine with Qt4.

2) If you've done the above, please post the specific output you're getting while running **make** from MinGW.

**Comment by autofire372** [comment] 2018-04-26 07:08
Did the above; compile still fails for the exact same reasons. These are the last few lines from make:

```
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x36fc): undefined reference to `glLinkProgram'
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x370b): undefined reference to `glGetProgramiv'
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x371c): undefined reference to `glGetProgramiv'
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x3748): undefined reference to `glGetProgramInfoLog'
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x37ab): undefined reference to `glDeleteShader'
common/libcommon.a(gx_util.cpp.o):gx_util.cpp:(.text+0x37b4): undefined reference to `glDeleteShader'
/usr/lib/../lib/libmsys-2.0.a(libcmain.o): In function `main':
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/lib/libcmain.c:37: undefined reference to `WinMain'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gbe_plus.dir/build.make:108: src/gbe_plus.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: src/CMakeFiles/gbe_plus.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by shonumi** [comment] 2018-04-26 10:08
GCC is complaining about OpenGL. Make sure you have GLEW installed.

**Comment by autofire372** [comment] 2018-04-26 20:00
Finally got it to build...and promptly discovered that GBE+ will not run outside of MinGW, as I get the following error, even with MinGW's bin directory added to my PATH:

"The procedure entry point InflateValidate could not be located in the dynamic link library /path/to/bin/libpng16-16.dll."

**Comment by shonumi** [comment] 2018-04-26 21:48
Try putting any relevant DLLs next to the executable instead of relying on PATH. That's how the 1.2 build (and development builds) are released. Check out 1.2 for a list of DLLs you'll need to copy. Don't forget the **platforms** folder too if you want to run the Qt GUI.

**Comment by shonumi** [comment] 2018-06-12 07:28
Haven't been able to reproduce any of these build errors. Build-bot is up and running under msys2 as well, so I'm going to close this. Any issues likely stem from an incorrectly configured build environment.

**Closed by shonumi** 2018-06-12 07:28 UTC
